(function(g){var window=this;var Xya=function(a,b){var c=[];g.ri(b,function(a){try{var b=g.tD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.sD(b)&&c.push(a):c.push(a)},a);
return c},Yya=function(a,b){var c=Xya(a,b);
(0,g.G)(c,function(a){g.tD.prototype.remove.call(this,a)},a)},Zya=function(){var a=g.bH;
Yya(a,a.g.Vd(!0))},R7=function(a,b){g.R0.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.U=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},$ya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},aza=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},S7=function(){var a=$ya();
a&&a(!1,"No cast extension found")},T7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},U7=function(a){if(a>=g.Jra.length)S7();
else{var b=g.Jra[a],c="chrome-extension://"+b+g.Gra;0<=g.m2.indexOf(b)?aza(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,T7(c,S7)):U7(a+1)}):T7(c,function(){U7(a+1)})}},V7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},bza=function(){if(g.Hra){var a=2,b=$ya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;T7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",S7,c)}},cza=function(){if(V7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){bza();a({command:"cast.sender.init"});return}}if(!window.chrome||V7("Edge"))S7();else if(bza(),V7("Android")&&V7("Chrome/")&&window.navigator.presentation){a="";var b=g.Mh();55<=b?a="55":50<=b&&(a="50");T7("//www.gstatic.com/eureka/clank"+a+g.Gra,S7)}else U7(0)},dza=function(a){g.uG[a]&&(a=g.uG[a],(0,g.G)(a,function(a){g.sG[a]&&delete g.sG[a]}),a.length=0)},eza=function(a){var b=g.rG();
if(b)if(b.clear(a),a)dza(a);else for(var c in g.uG)dza(c)},fza=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Eg(a)||"";b&&(this.port=":"+b);this.domain=g.Dg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ya(a,"10.0")&&(this.o=!1))},gza=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},hza=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Za(a)},iza=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},jza=function(){var a=hza(),b=window.document.getElementById(a),c=b&&g.HF(b,"loaded");
c||b&&!c||(b=iza(a,function(){g.HF(b,"loaded")||(g.GF(b,"loaded","true"),g.yG(a),g.JE(g.Ea(eza,a),0))}))},kza=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.hL||a},W7=function(a){g.rH("cloudview",a)},X7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},Y7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},lza=function(a,b,c,d){var e=!1;
Y7()||(a=new g.sI(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.dH("yt-remote-cast-available",a);g.zG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){W7("onReceiverSelected: "+a.friendlyName);
g.dH("yt-remote-cast-receiver",a);g.zG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){W7("onReceiverResumed: "+a.friendlyName);
g.dH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){W7("onSessionChange: "+g.zH(a));
a||g.fH("yt-remote-cast-receiver");g.zG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
W7("cloudview.createSingleton_: "+e);return e},mza=function(a){W7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},nza=function(){W7("dispose");
var a=Y7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);mza(!1);g.wG(Z7);Z7.length=0},$7=function(){return!!g.eH("yt-remote-cast-installed")},oza=function(){var a=g.eH("yt-remote-cast-receiver");
return a?a.friendlyName:null},pza=function(){W7("clearCurrentReceiver");
g.fH("yt-remote-cast-receiver")},a8=function(a){g.rH("cloudview",a)},qza=function(){return $7()?Y7()?Y7().getCastSession():(a8("getCastSelector: Cast is not initialized."),null):(a8("getCastSelector: Cast API is not installed!"),null)},b8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},c8=function(){$7()?Y7()?b8()?(W7("Requesting cast selector."),Y7().requestSession()):(W7("Wait for cast API to be ready to request the session."),Z7.push(g.vG("yt-remote-cast2-api-ready",c8))):a8("requestCastSelector: Cast is not initialized."):
a8("requestCastSelector: Cast API is not installed!")},d8=function(a,b){b8()?Y7().setConnectedScreenStatus(a,b):a8("setConnectedScreenStatus called before ready.")},e8=function(a){W7("setCastInstalled_ "+a);
g.dH("yt-remote-cast-installed",a)},rza=function(a,b){Y7().init(a,b)},sza=function(a,b){e8(!0);
X7(!1);rza(a,function(a){a?(mza(!0),g.yG("yt-remote-cast2-api-ready")):(a8("Failed to initialize cast API."),e8(!1),g.fH("yt-remote-cast-available"),g.fH("yt-remote-cast-receiver"),nza());b(a)})},tza=function(a,b,c,d,e,f,k){kza()?lza(b,e,f,k)&&(X7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?sza(a,c):(window.__onGCastApiAvailable=function(b,d){b?sza(a,c):(a8("Failed to load cast API: "+d),e8(!1),X7(!1),g.fH("yt-remote-cast-available"),g.fH("yt-remote-cast-receiver"),nza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):jza():cza())):W7("Cannot initialize because not running Chrome")},g8=function(a,b){g.iG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.HB;this.A=this.o=null;this.I=(0,g.z)(this.ZN,this);this.F=(0,g.z)(this.rl,this);this.G=(0,g.z)(this.YN,this);this.J=(0,g.z)(this.mO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ku,this),uza(this))):c=3;0!=c&&(b?this.ku(c):g.JE((0,g.z)(function(){this.ku(c)},this),0));
var d=qza();d&&f8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},h8=function(a){return new g.yI(a.B.getPlayerContextData())},uza=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ea(this.qQ,a),this))},a)},vza=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},i8=function(a,b){50>a.C.Ic()&&g.JB(a.C,b)},k8=function(a,b,c){var d=h8(a);
g.AI(d,c);-1E3!=d.g&&(d.g=b);j8(a,d)},l8=function(a,b,c){a.B.sendMessage(b,c)},j8=function(a,b){vza(a);
a.B.setPlayerContextData(g.DI(b));uza(a)},f8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.rl(null));
a.A=b;a.A&&(m8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.rl(a.A.media[0]))},wza=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=h8(a);b.contentId!=d.videoId&&m8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.AI(d,a.o.getEstimatedTime());j8(a,d)}else m8("No cast media video. Ignoring state update.")},m8=function(a){g.rH("CP",a)},n8=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),l8(this,b,c))},a)},o8=function(a){g.EH.call(this,"ScreenServiceProxy");
this.cd=a;this.o=[];this.o.push(this.cd.$_s("screenChange",(0,g.z)(this.ET,this)));this.o.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.WP,this)))},p8=function(){return g.x("yt.mdx.remote.currentScreenId_")},q8=function(a){g.rH("remote",a)},r8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},s8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},xza=function(){var a=s8();
if(g.Xb(a)){a=g.KH();var b=g.eH("yt-remote-session-name")||"",c=g.eH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},yza=function(a){a?(g.dH("yt-remote-session-app",a.app),g.dH("yt-remote-session-name",a.name)):(g.fH("yt-remote-session-app"),g.fH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},t8=function(){return g.x("yt.mdx.remote.connection_")},u8=function(){var a=t8();
return!!a&&3!=a.getProxyState()},zza=function(){return g.x("yt.mdx.remote.connectData_")},w8=function(){if(!v8){var a=g.x("yt.mdx.remote.screenService_");
v8=a?new o8(a):null}return v8},x8=function(){var a=g.LH();
if(!a)return null;var b=w8().ee();return g.DH(b,a)},y8=function(){var a=p8();
if(!a)return null;var b=w8().ee();return g.DH(b,a)},Aza=function(){var a=w8().cd.$_gos();
var b=y8();b&&t8()&&(g.CH(a,b)||a.push(b));return gza(a)},Bza=function(){var a=Aza(),b=y8();
b||(b=x8());return g.fb(a,function(a){return b&&g.wH(b,a.key)?!0:!1})},z8=function(){var a=Bza();
!a&&$7()&&oza()&&(a={key:"cast-selector-receiver",name:oza()});return a},Cza=function(){var a=Aza();
$7()&&g.eH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Dza=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},B8=function(a){var b=t8();
r8(null);a||Dza("");g.ua("yt.mdx.remote.connection_",a,void 0);A8&&((0,g.G)(A8,function(b){b(a)}),A8.length=0);
b&&!a?g.zG("yt-remote-connection-change",!1):!b&&a&&g.zG("yt-remote-connection-change",!0)},D8=function(a,b){y8()&&y8();
Dza(a.id);var c=new g.JI(C8,a,s8());c.connect(b,zza());c.subscribe("beforeDisconnect",function(a){g.zG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){t8()&&B8(null)});
B8(c)},Eza=function(){var a=x8();
a?(q8("Resume connection to: "+g.zH(a)),D8(a,0)):(g.SH(),pza(),q8("Skipping connecting because no session screen found."))},E8=function(){b8()?Y7().stopSession():a8("stopSession called before API ready.");
var a=t8();a&&(a.disconnect(1),B8(null))},Fza=function(a){q8("remote.onCastSessionChange_: "+g.zH(a));
if(a){var b=y8();b&&b.id==a.id?d8(b.id,"YouTube TV"):(b&&E8(),D8(a,1))}else t8()&&E8()},Gza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.aE("MDX_CONFIG")||b;g.bH&&Zya();g.MH();C8||(C8=new fza(b?b.loungeApiHost:void 0),g.UH()&&(C8.g="/api/loungedev"));A8||(A8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",A8,void 0));xza();var c=w8();if(!c){var d=new g.eI(C8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=w8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);tza(a,d,function(a){a?p8()&&d8(p8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.zG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),q8("Initializing: "+g.vg(b)),F8.push(g.vG("yt-remote-cast2-availability-change",function(){g.zG("yt-remote-receiver-availability-change")})),F8.push(g.vG("yt-remote-cast2-receiver-selected",function(){r8(null);
g.zG("yt-remote-auto-connect","cast-selector-receiver")})),F8.push(g.vG("yt-remote-cast2-receiver-resumed",function(){g.zG("yt-remote-receiver-resumed","cast-selector-receiver")})),F8.push(g.vG("yt-remote-cast2-session-change",Fza)),F8.push(g.vG("yt-remote-connection-change",function(a){a?d8(p8(),"YouTube TV"):x8()||(d8(null,null),pza())})),a=s8(),b.isAuto&&(a.id+="#dial"),g.oF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),q8(" -- with channel params: "+
g.vg(a)),yza(a),c.start(),p8()||Eza())},G8=function(a,b,c){g.L.call(this);
this.F=a;this.U=b;this.o=new g.fG(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.pP);this.o.P(b,"captionschanged",this.XN);this.o.P(b,"captionssettingschanged",this.lC);this.o.P(b,"videoplayerreset",this.so);this.o.P(b,"mdxautoplaycancel",this.EG);this.N=this.o.P(b,"onVolumeChange",this.DA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.QA,this);c.subscribe("remotePlayerChange",this.tl,this);c.subscribe("remoteQueueChange",this.so,this);c.subscribe("autoplayUpNext",this.qA,
this);c.subscribe("previousNextChange",this.NA,this);c.subscribe("nowAutoplaying",this.FA,this);c.subscribe("autoplayDismissed",this.pA,this);this.suggestion=null;this.G=new g.LQ(64);this.A=new g.vt(this.gC,500,this);g.M(this,this.A);this.B=new g.vt(this.hC,1E3,this);g.M(this,this.B);this.C={};this.J=new g.vt(this.KC,1E3,this);g.M(this,this.J);this.I=new g.mk(this.LK,1E3,this);g.M(this,this.I);this.L=g.y;this.lC();this.so();this.tl()},H8=function(a,b){var c=a.F,d=a.U.ga().lengthSeconds;
c.I=b||0;c.g.V("progresssync",b,d)},Hza=function(a){H8(a,0);
a.A.stop();I8(a,new g.LQ(64))},K8=function(a,b){if(J8(a)&&!a.D){var c=null;
b&&(c={style:a.U.oi()},g.dc(c,b));a.g.ZB(a.U.ga().videoId,c);a.C=h8(a.g).o}},L8=function(a,b){var c=a.U.Pf();
if(c){var d=c.ae();var e=c.listId.toString()}c=a.g;var f=a.U.ga().videoId,k=d;d=a.U.ga().playerParams;var l=h8(c),m=e||l.listId;k=k||0;var n={videoId:f,currentIndex:k};g.CI(l,f,k);g.t(b)&&(g.AI(l,b),n.currentTime=b);g.t(m)&&(n.listId=m);null!=d&&(n.playerParams=d);l8(c,"setPlaylist",n);e||j8(c,l);I8(a,new g.LQ(1))},Iza=function(a,b){if(b){var c=a.U.uc("captions","tracklist",{Xx:1});
c&&c.length?(a.U.Dd("captions","track",b),a.D=!1):(a.U.fl("captions"),a.D=!0)}else a.U.Dd("captions","track",{})},J8=function(a){return h8(a.g).videoId==a.U.ga().videoId},I8=function(a,b){a.B.stop();
var c=a.G;if(!g.QQ(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.U;g.J1(e.app,d,e.playerType)}a.G=b;Jza(a.F,c,b)}},X8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.fE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.zX(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);Kza(this,g.xW(a))},Kza=function(a,b){if(3==a.A.Wa()){var c={RECEIVER_NAME:a.A.uc("remote","currentReceiver").name};
c=g.W(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.W(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},i9=function(a){g.rX.call(this,a);
this.A={key:g.BH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.LQ(64);this.I=0;var b=g.qW(a).G;b&&(b=b.A&&b.A.g)&&(b=new R7(a,b),g.M(this,b));b=new X8(a);g.M(this,b);g.QW(a,b.element,4)},Jza=function(a,b,c){a.F=c;
a.g.V("presentingplayerstatechange",new g.VQ(c,b))},j9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)E8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Pf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.gc(l).videoId}else k=[e];f=a.g.getCurrentTime();c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,index:Math.max(a.g.hz(),0),currentTime:0==f?void 0:f}}else c=null;q8("Connecting to: "+g.vg(b));"cast-selector-receiver"==b.key?(r8(c||null),b8()?Y7().setLaunchParams(c||null):a8("setLaunchParams called before ready.")):!c&&u8()&&p8()==b.key?g.zG("yt-remote-connection-change",
!0):(E8(),r8(c||null),c=w8().ee(),(c=g.DH(c,b.key))&&D8(c,1))}};
g.p(R7,g.R0);R7.prototype.I=function(){var a=this.U.uc("remote","receivers");a&&1<a.length&&!this.U.uc("remote","quickCast")?(this.F=g.Gb(a,this.B,this),g.S0(this,(0,g.J)(a,this.B)),a=this.U.uc("remote","currentReceiver"),this.kf(this.B(a)),this.enable(!0)):this.enable(!1)};
R7.prototype.B=function(a){return a.key};
R7.prototype.jf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
R7.prototype.rd=function(a){g.R0.prototype.rd.call(this,a);this.U.Dd("remote","currentReceiver",this.F[a]);this.A.Lb()};
g.h=fza.prototype;g.h.Yh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Ng(b+a,{})};
g.h.iu=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Tb:g.Ea(this.zT,c,!0),onError:g.Ea(this.yT,d),Fd:g.Ea(this.AT,d)};b&&(c.Mb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.ZE(a,c)};
g.h.zT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.yT=function(a,b){a(Error("Request error: "+b.status))};
g.h.AT=function(a){a(Error("request timed out"))};
var Z7=[];g.A(g8,g.iG);g.h=g8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,n8(this,"play")):l8(this,"play"),k8(this,1,g.BI(h8(this))),this.V("remotePlayerChange")):i8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,n8(this,"pause")):l8(this,"pause"),k8(this,2,g.BI(h8(this))),this.V("remotePlayerChange")):i8(this,this.pause)};
g.h.VC=function(a){if(1==this.g){if(this.o){var b=h8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,n8(this,"seekTo",{newTime:a}))}else l8(this,"seekTo",{newTime:a});k8(this,3,a);this.V("remotePlayerChange")}else i8(this,g.Ea(this.VC,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,n8(this,"stopVideo")):l8(this,"stopVideo");var a=h8(this);a.index=-1;a.videoId="";g.zI(a);j8(this,a);this.V("remotePlayerChange")}else i8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=h8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){m8("set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){m8("set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);l8(this,"setVolume",e)}c.muted=b;c.volume=a;j8(this,c)}else i8(this,g.Ea(this.setVolume,a,b))};
g.h.ZB=function(a,b){if(1==this.g){var c=h8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.vg(b.style),g.dc(d,c.o));l8(this,"setSubtitlesTrack",d);j8(this,c)}else i8(this,g.Ea(this.ZB,a,b))};
g.h.ju=function(a,b){if(1==this.g){l8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qc.id});var c=h8(this);c.audioTrackId=b.Qc.id;j8(this,c)}else i8(this,g.Ea(this.ju,a,b))};
g.h.UC=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);g.CI(c,a,b);j8(this,c)}l8(this,"previous")}else i8(this,g.Ea(this.UC,a,b))};
g.h.TC=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);g.CI(c,a,b);j8(this,c)}l8(this,"next")}else i8(this,g.Ea(this.TC,a,b))};
g.h.rw=function(){1==this.g?l8(this,"dismissAutoplay"):i8(this,this.rw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.V("proxyStateChange",a,this.g)}g8.Z.dispose.call(this)};
g.h.X=function(){vza(this);this.B=null;this.C.clear();f8(this,null);g8.Z.X.call(this)};
g.h.ku=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.KB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.qQ=function(a,b){this.V(a,b)};
g.h.ZN=function(a){if(!a)this.rl(null),f8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=h8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)m8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,j8(this,b)}};
g.h.rl=function(a){m8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),wza(this),this.V("remotePlayerChange")};
g.h.YN=function(a){a?(wza(this),this.V("remotePlayerChange")):this.rl(null)};
g.h.mO=function(){var a=qza();a&&f8(this,a)};
g.h.Zb=function(a){g.rH("CP",a)};
g.A(o8,g.EH);g.h=o8.prototype;g.h.ee=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.sp=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Zo=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.cd.$_ubk(this.o[a]);this.o.length=0;this.cd=null;o8.Z.X.call(this)};
g.h.ET=function(){this.V("screenChange")};
g.h.WP=function(){this.V("onlineScreenChange")};
var C8=null,A8=null,F8=[],v8=null;g.p(G8,g.L);g.h=G8.prototype;g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.L();this.g.unsubscribe("proxyStateChange",this.QA,this);this.g.unsubscribe("remotePlayerChange",this.tl,this);this.g.unsubscribe("remoteQueueChange",this.so,this);this.g.unsubscribe("autoplayUpNext",this.qA,this);this.g.unsubscribe("previousNextChange",this.NA,this);this.g.unsubscribe("nowAutoplaying",this.FA,this);this.g.unsubscribe("autoplayDismissed",this.pA,this);this.g=this.F=null};
g.h.Xy=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(J8(this)){if(1081!=h8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":h8(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.ej(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.g.ju(this.U.ga().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.U.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.g.ju(this.U.ga().videoId,c)}};
g.h.XN=function(a){this.Xy("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.lC=function(){var a=this.U.uc("captions","track");g.Xb(a)||K8(this,a)};
g.h.DA=function(a){if(J8(this)){this.g.unsubscribe("remotePlayerChange",this.tl,this);var b=Math.round(a.volume);a=!!a.muted;var c=h8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.J.start();this.g.subscribe("remotePlayerChange",this.tl,this)}};
g.h.pP=function(){g.Xb(this.C)||Iza(this,this.C);this.D=!1};
g.h.QA=function(a,b){this.B.stop();2==b&&this.hC()};
g.h.tl=function(){if(J8(this)){this.A.stop();var a=h8(this.g);switch(a.g){case 1081:I8(this,new g.LQ(8));break;case 1:this.gC();I8(this,new g.LQ(8));break;case 1083:case 3:I8(this,new g.LQ(9));break;case 0:I8(this,new g.LQ(2));this.I.stop();H8(this,this.U.ga().lengthSeconds);break;case 1082:I8(this,new g.LQ(4));break;case 2:I8(this,new g.LQ(4));H8(this,g.BI(a));break;case -1:I8(this,new g.LQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},I8(this,new g.LQ(128,
a))}a=h8(this.g).o;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,Iza(this,a));a=h8(this.g);-1==a.volume||Math.round(this.U.getVolume())==a.volume&&this.U.isMuted()==a.muted||this.J.isActive()||this.KC()}else Hza(this)};
g.h.NA=function(){this.U.V("mdxpreviousnextchange")};
g.h.so=function(){J8(this)||Hza(this)};
g.h.EG=function(){this.g.rw()};
g.h.qA=function(a){a&&(a=g.ZE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},Tb:(0,g.z)(this.qR,this)}))&&(this.L=(0,g.z)(a.abort,a))};
g.h.qR=function(a,b){var c=new g.NP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.U.V("mdxautoplayupnext",c)};
g.h.FA=function(a){(0,window.isNaN)(a)||this.U.V("mdxnowautoplaying",a)};
g.h.pA=function(){this.U.V("mdxautoplaycanceled")};
g.h.LK=function(a,b){-1==h8(this.g).g?L8(this,a):b&&this.g.VC(a)};
g.h.KC=function(){if(J8(this)){var a=h8(this.g);this.o.Ca(this.N);a.muted?this.U.mute():this.U.Qf();this.U.setVolume(a.volume);this.N=this.o.P(this.U,"onVolumeChange",this.DA)}};
g.h.gC=function(){this.A.stop();if(!this.g.ka()){var a=h8(this.g);a.jb()&&I8(this,new g.LQ(8));H8(this,g.BI(a));this.A.start()}};
g.h.hC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(X8,g.Y);X8.prototype.B=function(a){Kza(this,a.state)};g.p(i9,g.rX);g.h=i9.prototype;g.h.create=function(){Gza(g.PN(g.X(this.g)));this.D.push(g.vG("yt-remote-before-disconnect",this.TN,this));this.D.push(g.vG("yt-remote-connection-change",this.zQ,this));this.D.push(g.vG("yt-remote-receiver-availability-change",this.OA,this));this.D.push(g.vG("yt-remote-auto-connect",this.xQ,this));this.D.push(g.vG("yt-remote-receiver-resumed",this.wQ,this));this.OA()};
g.h.load=function(){this.g.Vp();g.rX.prototype.load.call(this);this.C=new G8(this,this.g,this.o);var a=zza();a=a?a.currentTime:0;var b=u8()?new g8(t8(),void 0):null;0==a&&b&&(a=g.BI(h8(b)));0!=a&&(this.I=a||0,this.g.V("progresssync",a,void 0));Jza(this,this.F,this.F);g.N1(this.g.app,6)};
g.h.unload=function(){this.g.V("mdxautoplaycanceled");this.B=this.A;g.Ze(this.C,this.o);this.o=this.C=null;g.rX.prototype.unload.call(this);g.N1(this.g.app,5)};
g.h.X=function(){g.wG(this.D);g.rX.prototype.X.call(this)};
g.h.Xk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.Xy.apply(this.C,[].concat([a],g.pa(c)))};
g.h.rH=function(){return this.loaded?this.C.suggestion:null};
g.h.Ff=function(){return this.o?h8(this.o).Ff:!1};
g.h.hasNext=function(){return this.o?h8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.oK=function(){var a=h8(this.o),b=this.g.ga();return{allowSeeking:this.g.dd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.F)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.F)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.F?a.B+((0,g.F)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.F)()-a.A)/1E3:a.D}};
g.h.pK=function(){this.o&&this.o.TC()};
g.h.qK=function(){this.o&&this.o.UC()};
g.h.TN=function(a){1==a&&(this.J=this.o?h8(this.o):null)};
g.h.zQ=function(){var a=u8()?new g8(t8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ye(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.fz(a.videoId,g.BI(a)));this.g.V("videodatachange","newdata",this.g.ga(),3)};
g.h.OA=function(){this.G=[this.A].concat(Cza());var a=z8()||this.A;j9(this,a);this.g.va("onMdxReceiversChange")};
g.h.xQ=function(){var a=z8();j9(this,a)};
g.h.wQ=function(){this.B=z8()};
g.h.nK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?c8():j9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&c8(),!0):!1}};
g.h.rK=function(){l8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.td=function(){return!1};g.WZ.remote=i9;})(_yt_player);
